# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 02:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_auto_20160127_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='autors',
            field=models.ManyToManyField(blank=True, to='catalogo.Autor'),
        ),
    ]
